linters-settings:
  errcheck:
    check-type-assertions: true
  forbidigo:
    forbid:
      - '^fmt\.Print'
      - '^log\.'
      - '^print$'
      - '^println$'
      - '^panic$'
  godox:
    # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
    # temporary hacks, and use godox to prevent committing them.
    keywords: [FIXME]
  varnamelen:
    ignore-decls:
      - T any
      - i int
      - wg sync.WaitGroup
      - id string
linters:
  enable-all: true
  disable:
    - cyclop            # covered by gocyclo
    - depguard          # unnecessary for small libraries
    - err113            # way too noisy
    - exhaustruct       # many exceptions
    - funlen            # rely on code review to limit function length
    - gochecknoglobals  # many exceptions
    - gocognit          # dubious "cognitive overhead" quantification
    - gofumpt           # prefer standard gofmt
    - goimports         # rely on gci instead
    - inamedparam       # not standard style
    - interfacebloat    # many exceptions
    - ireturn           # "accept interfaces, return structs" isn't ironclad
    - lll               # don't want hard limits for line length
    - maintidx          # covered by gocyclo
    - mnd               # many exceptions
    - nilnil            # allow this
    - nlreturn          # generous whitespace violates house style
    - testifylint       # does not want us to use assert
    - testpackage       # internal tests are fine
    - thelper           # we want to print out the whole stack
    - wrapcheck         # don't _always_ need to wrap errors
    - wsl               # generous whitespace violates house style
issues:
  exclude-dirs-use-default: false
  exclude-rules:
    - linters:
        - containedctx
      path: xos/xexec/process.go
    - linters:
        - gosec
      test: G204
      path: xos/xexec/xexec.go
    - linters:
        - varnamelen
      path: xslices/xslices.go
    - linters:
        - gocritic
        - nestif
        - varnamelen
      path: xstrings/xstrings.go
    - linters:
        - forbidigo
      text: panic
      path: xsync/xsync.go
    - linters:
        - varnamelen
      path: xsync/xsync.go
